import { createContext } from "react";

export const apContext = createContext({
    setAdminUser: () => { },
    adminUser: '',
    handleInputs: () => { },
    handleFormSubmit: () => { },
    getUserID: () => { },
    makeJsonFile: () => { },
    handleCancleButton: () => { },
    getNestedChildren: () => { },
    accessMenu: '',
    setAccessMenu: () => { },
    searchItems: () => { },
    searchInput: '',
    setSearchInput: () => { },
    filteredResults: '',
    setFilteredResults: () => { },
    handleAllAccess: () => { },
    handleAllUsernames: () => { },
    adminUsers: '',
    setAdminUsers:() => { },
    adminAccess: '',
    setAdminAccess:() => { },
    filteringAccess: () => { },
    levelAccess: '',
    setLevelAccess: () => { },
    handleArrowClick: () => { },
    level1: '',
    setLevel1:  () => { },
    handleUserPermissions: () => { },
    checkUserPerms: () => { },
    numOfUSers: '',
    setNumOfUsers: () => { },
    handleDeleteOrAddAccess: () => { },
    prevAccess: '',
    deleteObj: '',
    finalDeleteObj: ''
});